### ISSUE TITLE
What is the best way to develop this locally ?

### ISSUE THREAD

**Issue by simo97** [2trc/katika#2]
it's better to develop with the vagrant box up or without it at all ? From the doc it seem that the vagrant box is mainly usefull for testing. 
But if i run it up and i try to edit source codes in the folder, is it getting updated inside the box automatically ?

**Comment by 2trc** [comment]
Hi @simo97 vagrant is not mandatory. It's more of a convenience to quickly get things up and running
Yes you can develop locally without vagrant
Also yes, the changes you make locally are reflected inside the vagrant machine under the folder `/vagrant`

**Comment by 2trc** [comment]
Closing the issue as there was no further comments
