### ISSUE TITLE
Vagrant Setup Issue

### ISSUE THREAD

**Issue by math-alpha** [2trc/katika#4]
<img width="1486" alt="image" src="https://user-images.githubusercontent.com/24694082/215195765-fa378595-8e9f-4529-ad89-c5993f2ca5ac.png">

After setting up the stack, I don't seem to understand why the port forwarding has some issues.

Upon investigation, I noticed that
- The files aren't copied into the VM
- There seems to be no process running

**Comment by math-alpha** [comment]
<img width="855" alt="image" src="https://user-images.githubusercontent.com/24694082/215197339-261df5d1-41d2-415c-8ff6-f0c49906f72b.png">

**Comment by 2trc** [comment]
Hi @math-alpha 
1.
The shared folder in the Guest OS should be at /vagrant and not /home/vagrant. That's the default configuration
2.
To start the server in the Guest OS try
`
cd /vagrant
python3.6 /vagrant/manage.py runserver 0.0.0.0:8000
`
Normally you should be within the Guest OS `curl localhost:8000` should work and in the Host OS `curl localhost:8002` should be ok

If not, did you get any error message during the installation process?

3.
You could add those commands in the cronjob so the web application is started automatically after each reboot. Something we can improve in the code to have in the installation process

Remi

**Comment by math-alpha** [comment]
Okay I will fix the /vagrant path (Not sure how that came about)

I didn't know I had to start the process manually.

So I cleared all installation issues. I think.

For the cron part, I am sure I got you well. Do you mean an automation script to start the stack or something for my local environment?

**Comment by 2trc** [comment]
Glad to hear!

Regarding cron, it's not mandatory here because during the development you'll have to stop and start the web application very often. But yes it's a Linux service for scheduling periodic tasks.
Have a look here for reboot specific tutorial https://phoenixnap.com/kb/crontab-reboot

More general tutorial: https://opensource.com/article/17/11/how-use-cron-linux
